name: Hello World

# Events
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Workflow / Jobs
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello
        run: echo "Hello World!"
        shell: bash
        
  bye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: bye
        run: echo "bye World!"
        shell: bash